import {createClient} from '@supabase/supabase-js';
import Chart from 'chart.js/auto';
import './style.css';
const root=document.querySelector('#app'),modal=document.querySelector('#modal');
const state={client:null,session:null,memberships:[],org:null,role:'viewer',currency:'KES',page:'overview',invoicePage:1,invoiceFilters:{},snapshot:null,draft:{},dirty:true,customers:[],importFile:null,importInspect:null,importPreview:null,charts:[],token:0,overviewFilters:{},overviewDraft:{},overviewRequest:0,overviewData:null};
const nav=[['overview','Overview','grid-1x2'],['invoices','Invoices','receipt'],['customers','Customers','people'],['imports','Imports','cloud-arrow-up'],['collections','Collections','wallet2'],['reports','Reports','bar-chart-line'],['history','History','clock-history'],['team','Team','person-gear']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>`<i class="bi bi-${name}" aria-hidden="true"></i>`;
const label=v=>String(v??'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Africa/Nairobi'}).format(new Date());
const money=v=>Number(v||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});
const shortDate=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00Z`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';
const timestamp=v=>v?new Date(v).toLocaleString('en-GB',{timeZone:'Africa/Nairobi',dateStyle:'medium',timeStyle:'short'}):'—';
const initials=v=>String(v||'M').split(/[\s@]+/).slice(0,2).map(s=>s[0]).join('').toUpperCase();
const writable=()=>['owner','admin','collector'].includes(state.role);
const admin=()=>['owner','admin'].includes(state.role);
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),4500);}
async function api(route,{method='GET',body,blob=false}={}){
 const {data,error}=await state.client.auth.getSession();if(error||!data.session)throw new Error('Session expired. Sign in again');
 const headers={Authorization:`Bearer ${data.session.access_token}`};if(state.org)headers['X-Organization-Id']=state.org;
 if(body&&!(body instanceof FormData))headers['Content-Type']='application/json';
 const response=await fetch(`/api${route}`,{method,headers,body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined});
 if(!response.ok){let err;try{err=await response.json();}catch{}throw new Error(err?.error||`Request failed (${response.status})`);}
 return blob?response:response.json();
}
function button(text,action,kind='secondary',ico='',extra=''){return `<button class="btn ${kind}" data-action="${action}" ${extra}>${ico?icon(ico):''}${text}</button>`;}
function heading(title,actions=''){return `<div class="page-head"><div><div class="eyebrow">Collections workspace</div><h1>${title}</h1></div><div class="actions">${actions}</div></div>`;}
function empty(text,ico='inbox',action=''){return `<div class="empty">${icon(ico)}${text}${action}</div>`;}
function loader(){return `<div class="loading"><div class="spinner"></div>Loading</div>`;}
function statuses(row){return `<div class="status-stack"><span class="tag ${row.payment_status==='paid'?'green':row.payment_status==='partial'?'blue':'amber'}">${label(row.payment_status)}</span>${row.payment_status!=='paid'?`<span class="tag ${['overdue','due_today'].includes(row.due_status)?'red':'amber'}">${label(row.due_status)}${row.due_status==='overdue'?` · ${row.overdue_days}d`:''}</span>`:''}</div>`;}
function invoiceTable(rows){
 return rows.length?`<div class="table-wrap"><table><thead><tr><th>Invoice / Source</th><th>Customer</th><th>Invoice date</th><th>Due date</th><th class="amount">Invoiced</th><th class="amount">Collected</th><th class="amount">Balance</th><th>Status</th><th>Action</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="link cell-main" data-action="invoice-detail" data-id="${esc(r.id)}">${esc(r.internal_number)}</button><span class="cell-sub">${esc(r.external_number||'—')}</span></td><td><span class="cell-main">${esc(r.customer_name)}</span><span class="cell-sub">${esc(r.customer_code)}</span></td><td>${shortDate(r.invoice_date)}</td><td>${shortDate(r.due_date)}</td><td class="amount">${money(r.amount)}</td><td class="amount">${money(r.paid_amount)}</td><td class="amount">${money(r.balance)}</td><td>${statuses(r)}</td><td><span class="tag ${r.operation_status==='actioned'?'green':r.operation_status==='disputed'?'red':''}">${label(r.operation_status)}</span></td><td>${writable()&&r.balance>0?button('Collect','collect','secondary small','',`data-id="${esc(r.id)}"`):button('View','invoice-detail','secondary small','',`data-id="${esc(r.id)}"`)}</td></tr>`).join('')}</tbody></table></div>`:empty('No invoices found','receipt');
}
function shell(){state.charts.forEach(c=>c.destroy());state.charts=[];
 const title=nav.find(n=>n[0]===state.page)?.[1]||'Overview';
 root.innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="#overview"><img src="/mark.svg" alt="Mary Collections"><div><strong>Mary</strong><span>Collections</span></div></a><div class="nav-caption">WORKSPACE</div><nav>${nav.filter(n=>n[0]!=='team'||admin()).map(([p,t,i])=>`<a href="#${p}" class="nav-link ${p===state.page?'active':''}">${icon(i)}${t}</a>`).join('')}</nav><div class="sidebar-bottom">${state.memberships.length>1?`<select id="org-select" aria-label="Organization">${state.memberships.map(m=>`<option value="${m.org_id}" ${m.org_id===state.org?'selected':''}>${esc(m.mc_organizations.name)}</option>`).join('')}</select>`:''}<div class="sidebar-rule"></div><div class="profile"><span class="avatar">${initials(state.session?.user.email)}</span><div><strong>${esc(state.session?.user.email)}</strong><small>${state.role}</small></div></div></div></aside><div class="content"><header class="topbar"><button class="icon-btn mobile-menu" data-action="menu" aria-label="Open navigation">${icon('list')}</button><div class="breadcrumb">Workspace ${icon('chevron-right')}<strong>${title}</strong></div><div class="topbar-right"><span>${shortDate(today())}</span><span class="tag pill green"><span class="dot"></span>Live</span><button class="icon-btn" data-action="signout" aria-label="Sign out" title="Sign out">${icon('box-arrow-right')}</button></div></header><main class="main" id="main">${loader()}</main></div></div>`;
}
function footer(){return `<footer class="footer"><span>Mary Collections</span><span>${state.currency} · Africa/Nairobi</span></footer>`;}
async function loadPage(){
 const token=++state.token;state.page=location.hash.slice(1)||'overview';if(!nav.some(n=>n[0]===state.page))state.page='overview';
 if(state.page==='team'&&!admin())state.page='overview';shell();
 try{
  if(state.page==='overview')await overview(token);
  else if(state.page==='invoices')await invoices(token);
  else if(state.page==='customers')await customersPage(token);
  else if(state.page==='imports')await importsPage(token);
  else if(['reports','history','collections'].includes(state.page))await reportPage(token);
  else if(state.page==='team')await teamPage(token);
 }catch(e){if(token===state.token)document.querySelector('#main').innerHTML=`${heading(label(state.page))}<div class="error">${esc(e.message)}</div>${button('Retry','reload','secondary','arrow-clockwise')}`;}
}
async function overview(token){
 await getCustomers();if(token!==state.token)return;
 const form=filterForm('invoices',state.overviewDraft).replace('id="filter-form"','id="overview-filter-form"').replace('id="filter-state"','id="overview-filter-state"').replace(' OK</button>',' Apply</button>');
 document.querySelector('#main').innerHTML=`${heading('Overview',writable()?button('Import','goto-import','secondary','cloud-arrow-up')+button('New invoice','new-invoice','','plus-lg'):'')}
 <div class="overview-toolbar"><div class="section-label">${icon('sliders')} Portfolio filters</div><label class="period-select">Period<select id="overview-period" aria-label="Overview period"><option value="custom">Custom / All dates</option><option value="month">This month</option><option value="quarter">Last 3 months</option><option value="year">This year</option></select></label></div>${form}
 <div class="error" id="overview-error" role="alert"></div><div id="overview-results" aria-live="polite">${loader()}</div>${footer()}`;
 await applyOverview(document.querySelector('#overview-filter-form'));
}
function compactMoney(v){const n=Number(v||0);return new Intl.NumberFormat('en-KE',{notation:'compact',maximumFractionDigits:1}).format(n);}
function criteriaChips(filters){return Object.entries(filters).filter(([k,v])=>v!==''&&v!=null&&k!=='sort').map(([k,v])=>{
 const value=k==='customer_id'?state.customers.find(c=>c.id===v)?.name||'Selected customer':k==='actor_id'?(state.actors||[]).find(a=>a.actor_id===v)?.actor_email||'Selected user':k==='invoice_id'?'Selected invoice':v;
 return `<span class="criteria-chip"><span>${esc(label(k.replace('_id','')))}</span> ${esc(label(value))}</span>`;
 }).join('')||'<span class="criteria-chip">All records</span>';}
function overviewKpi(title,value,ico,note,kind=''){return `<article class="kpi ${kind}"><div class="kpi-head"><span>${title}</span><span class="kpi-icon">${icon(ico)}</span></div><div class="kpi-value"><span class="currency">${state.currency}</span>${money(value)}</div><small>${note}</small></article>`;}
function monthRange(period){const start=`${period}-01`,d=new Date(`${start}T12:00:00Z`),end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0));return [start,end.toISOString().slice(0,10)];}
function drillToInvoices(extra={},description='Selected chart segment'){state.invoiceFilters={...state.overviewFilters,...extra};state.invoicePage=1;toast(`${description} · opening matching invoices`);location.hash='invoices';}
function agingFilters(bucket){if(bucket==='Not due')return {due_status:'not_due',overdue_min:'',overdue_max:''};if(bucket==='Due today')return {due_status:'due_today',overdue_min:'',overdue_max:''};if(bucket==='1–30 days')return {due_status:'overdue',overdue_min:'1',overdue_max:'30'};if(bucket==='31–60 days')return {due_status:'overdue',overdue_min:'31',overdue_max:'60'};if(bucket==='61–90 days')return {due_status:'overdue',overdue_min:'61',overdue_max:'90'};if(bucket==='90+ days')return {due_status:'overdue',overdue_min:'91',overdue_max:''};return {};}
async function applyOverview(form){
 if(!form?.isConnected)return;clearTimeout(state.overviewTimer);
 const values=Object.fromEntries(new FormData(form)),request=++state.overviewRequest,token=state.token;
 state.overviewDraft=values;document.querySelector('#overview-filter-state').textContent='Updating…';document.querySelector('#overview-error').textContent='';
 try{
 const data=await api('/dashboard',{method:'POST',body:{filters:values}});
 if(request!==state.overviewRequest||token!==state.token||!form.isConnected||JSON.stringify(Object.fromEntries(new FormData(form)))!==JSON.stringify(values))return;
 state.overviewFilters=values;state.overviewData=data;renderOverview(data);
 document.querySelector('#overview-filter-state').innerHTML=`${icon('check-circle')} Applied`;
 }catch(e){if(request===state.overviewRequest&&token===state.token&&form.isConnected){document.querySelector('#overview-error').textContent=e.message;document.querySelector('#overview-filter-state').textContent='Unapplied changes';if(document.querySelector('#overview-results .loading'))document.querySelector('#overview-results').innerHTML=empty('No overview available','bar-chart');}}
}
function queueOverview(form){state.overviewRequest++;state.overviewDraft=Object.fromEntries(new FormData(form));document.querySelector('#overview-filter-state').textContent='Updating…';clearTimeout(state.overviewTimer);state.overviewTimer=setTimeout(()=>applyOverview(form),350);}
function renderOverview(data){
 state.charts.forEach(c=>c.destroy());state.charts=[];
 const s=data.summary,rate=s.invoiced?100*s.collected/s.invoiced:0,risk=s.outstanding?100*s.overdue/s.outstanding:0;
 const months=data.monthly.map(m=>new Date(m.period+'-01T12:00:00Z').toLocaleDateString('en-GB',{month:'short',year:'2-digit'}));
 const mix=['paid','partial','unpaid'].map(status=>data.payment_mix.find(p=>p.status===status)||{status,invoices:0,outstanding:0});
 const metric=(title,value,note,percent,color)=>`<div class="portfolio-metric"><div><span>${title}</span><strong>${value}</strong></div><div class="metric-track"><span style="width:${Math.max(0,Math.min(100,percent))}%;background:${color}"></span></div><small>${note}</small></div>`;
 document.querySelector('#overview-results').innerHTML=`<div class="applied-strip"><div class="criteria-chips">${criteriaChips(state.overviewFilters)}</div><span class="as-of">As of ${shortDate(data.as_of_date)}</span></div>
 <div class="kpis">${overviewKpi('Outstanding',s.outstanding,'wallet2',`${s.count-s.paid_count} open invoices`,'featured')}${overviewKpi('Collected',s.collected,'check2-circle',`${s.paid_count} paid invoices`,'collected')}${overviewKpi('Overdue',s.overdue,'exclamation-circle',`${s.overdue_count} overdue invoices`,'overdue')}${overviewKpi('Total invoiced',s.invoiced,'receipt',`${s.count} selected invoices`)}</div>
 <section class="portfolio-strip">${metric('Collection rate',rate.toFixed(1)+'%',`${s.paid_count} of ${s.count} invoices paid`,rate,'#15856a')}${metric('Overdue exposure',risk.toFixed(1)+'%',`${state.currency} ${money(s.overdue)} overdue`,risk,'#d16b63')}${metric('Partial balance',`${state.currency} ${compactMoney(s.partial_balance)}`,`${mix[1].invoices} partially paid invoices`,s.outstanding?100*s.partial_balance/s.outstanding:0,'#6b83cc')}</section>
 <div class="overview-charts"><section class="panel trend-panel"><div class="panel-head"><div class="chart-heading"><h2>Invoice & collection trends</h2><small>Collection history · selected invoices</small></div><span class="chart-badge">${months[0]||'—'} — ${months.at(-1)||'—'}</span></div><div class="panel-body"><div class="chart-wrap"><canvas id="trend-chart" role="img" aria-label="Monthly invoice and collection amounts for applied filters"></canvas></div><div class="chart-key"><span><i style="background:#225c63"></i>Invoiced</span><span><i style="background:#81b68e"></i>Collected</span></div></div></section>
 <section class="panel"><div class="panel-head"><div class="chart-heading"><h2>Payment mix</h2><small>Selected invoice count</small></div>${icon('pie-chart')}</div><div class="panel-body"><div class="donut-shell"><div class="chart-wrap donut-chart"><canvas id="payment-chart" role="img" aria-label="${mix.map(p=>`${label(p.status)}: ${p.invoices}`).join(', ')}"></canvas></div><div class="donut-total"><strong>${s.count}</strong><span>Invoices</span></div></div><div class="mix-legend">${mix.map((p,i)=>`<div><span><i style="background:${['#16856a','#7587c7','#e5b465'][i]}"></i>${label(p.status)}</span><strong>${p.invoices}</strong></div>`).join('')}</div></div></section>
 <section class="panel"><div class="panel-head"><div class="chart-heading"><h2>Outstanding by age</h2><small>${state.currency} · current balances</small></div><span class="chart-badge">${s.overdue_count} overdue</span></div><div class="panel-body"><div class="chart-wrap"><canvas id="aging-chart" role="img" aria-label="Outstanding balances by due age"></canvas></div></div></section>
 <section class="panel"><div class="panel-head"><div class="chart-heading"><h2>Customer balances</h2><small>Largest outstanding balances · ${state.currency}</small></div>${icon('people')}</div><div class="panel-body"><div class="chart-wrap"><canvas id="customer-chart" role="img" aria-label="Largest customer balances for applied filters"></canvas>${!data.top_customers.length?'<div class="chart-empty">No outstanding balances</div>':''}</div></div></section></div>
 <section class="panel"><div class="panel-head"><div class="chart-heading"><h2>Overdue invoices</h2><small>${s.overdue_count} matching invoices · ${state.currency}</small></div><a class="link" href="#invoices" data-action="overdue-invoices">View all ${icon('arrow-up-right')}</a></div>${invoiceTable(data.overdue_rows)}</section>`;
 const axis={border:{display:false},grid:{color:'#edf1f0'},ticks:{font:{size:11},color:'#7d9092',callback:v=>compactMoney(v)}};
 const pointer={onHover:(event,elements)=>{event.native.target.style.cursor=elements.length?'pointer':'default';}};
 const cartesian={responsive:true,maintainAspectRatio:false,animation:false,...pointer,plugins:{legend:{display:false},tooltip:{backgroundColor:'#153e44',padding:12,cornerRadius:8,callbacks:{label:c=>`${c.dataset.label}: ${state.currency} ${money(c.parsed.y)}`,footer:()=> 'Click to view matching records'}}},scales:{x:{grid:{display:false},border:{display:false},ticks:{color:'#7d9092',font:{size:11},maxRotation:0,autoSkip:true}},y:{...axis,beginAtZero:true}}};
 state.charts.push(new Chart(document.querySelector('#trend-chart'),{type:'bar',data:{labels:months,datasets:[{label:'Invoiced',data:data.monthly.map(m=>m.invoiced),backgroundColor:'#225c63',borderRadius:5,maxBarThickness:32,order:2},{type:'line',label:'Collected',data:data.monthly.map(m=>m.collected),borderColor:'#81b68e',backgroundColor:'#81b68e26',pointBackgroundColor:'#fff',pointBorderWidth:2,pointRadius:4,pointHoverRadius:6,tension:.3,fill:true,order:1}]},options:{...cartesian,onClick:(event,elements)=>{if(!elements.length)return;const item=elements[0],period=data.monthly[item.index]?.period;if(!period)return;const [date_from,date_to]=monthRange(period);drillToInvoices({date_from,date_to},`${item.datasetIndex===0?'Invoiced':'Collected'} · ${months[item.index]}`);}}}));
 state.charts.push(new Chart(document.querySelector('#payment-chart'),{type:'doughnut',data:{labels:mix.map(p=>label(p.status)),datasets:[{data:mix.map(p=>p.invoices),backgroundColor:['#16856a','#7587c7','#e5b465'],borderWidth:3,borderColor:'#fff',borderRadius:5,hoverOffset:7}]},options:{responsive:true,maintainAspectRatio:false,animation:false,...pointer,cutout:'78%',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.label}: ${c.raw} invoices`,footer:()=> 'Click to view invoices'}}},onClick:(event,elements)=>{if(!elements.length)return;const status=mix[elements[0].index]?.status;if(status)drillToInvoices({payment_status:status},`${label(status)} invoices`);}}}));
 const bars=(id,labels,values,colors,onClick)=>state.charts.push(new Chart(document.querySelector(id),{type:'bar',data:{labels,datasets:[{label:'Outstanding',data:values,backgroundColor:colors,borderRadius:7,maxBarThickness:19,hoverBorderWidth:2,hoverBorderColor:'#153e44'}]},options:{...cartesian,indexAxis:'y',onClick:(event,elements)=>{if(elements.length)onClick(elements[0].index);},plugins:{...cartesian.plugins,tooltip:{...cartesian.plugins.tooltip,callbacks:{label:c=>`${state.currency} ${money(c.parsed.x)}`,footer:()=> 'Click to view matching invoices'}}},scales:{x:{...axis,beginAtZero:true},y:{grid:{display:false},border:{display:false},ticks:{color:'#526f73',font:{size:11},callback:function(v){const name=this.getLabelForValue(v);return name.length>22?name.slice(0,21)+'…':name;}}}}}}));
 bars('#aging-chart',data.aging.map(a=>a.bucket),data.aging.map(a=>a.amount),['#a2bfaf','#e4bf72','#e2a36e','#d98a71','#cf716b','#b9505e'],index=>{const bucket=data.aging[index]?.bucket;if(bucket)drillToInvoices(agingFilters(bucket),bucket);});
 bars('#customer-chart',data.top_customers.map(c=>c.customer_name),data.top_customers.map(c=>c.outstanding),['#225c63','#397d80','#629896','#83ada4','#acc4b2','#cfdbba'],index=>{const customer=data.top_customers[index];if(customer)drillToInvoices({customer_id:customer.customer_id},customer.customer_name);});
}
function inputField(key,title,type='text',v='',extra=''){return `<label>${title}<input type="${type}" name="${key}" value="${esc(v)}" ${extra}></label>`;}
function selectField(key,title,options,v='',extra=''){return `<label>${title}<select name="${key}" ${extra}><option value="">All</option>${options.map(o=>{const value=Array.isArray(o)?o[0]:o;return `<option value="${esc(value)}" ${value===v?'selected':''}>${esc(Array.isArray(o)?o[1]:label(o))}</option>`;}).join('')}</select></label>`;}
function customerOptions(){return state.customers.map(c=>[c.id,`${c.name} · ${c.customer_code}`]);}
async function getCustomers(){state.customers=await api('/customers');return state.customers;}
function filterForm(kind,values={}){
 const inv=kind==='invoices',hist=kind==='history';
 return `<form id="filter-form" data-kind="${kind}" class="panel"><div class="filters">
 ${inputField('search',hist?'Name, invoice or user':'Name or invoice','search',values.search||'')}
 ${selectField('customer_id','Customer',customerOptions(),values.customer_id)}
 ${inputField(inv?'date_from':'event_from',inv?'Invoice date from':hist?'History from':'Payment date from','date',values[inv?'date_from':'event_from']||'')}
 ${inputField(inv?'date_to':'event_to',inv?'Invoice date to':hist?'History to':'Payment date to','date',values[inv?'date_to':'event_to']||'')}
 ${inv?`${selectField('payment_status','Payment',['unpaid','partial','paid'],values.payment_status)}${selectField('due_status','Due',['not_due','due_today','overdue','settled'],values.due_status)}${inputField('amount_min','Invoice amount from','number',values.amount_min||'','min="0" step="0.01"')}${inputField('amount_max','Invoice amount to','number',values.amount_max||'','min="0" step="0.01"')}`:hist?`${selectField('action','Action',['customer_created','customer_updated','invoice_created','invoice_updated','payment_recorded','payment_reversed','import_completed','member_updated','report_applied','report_exported'],values.action)}${selectField('actor_id','User',(state.actors||[]).map(a=>[a.actor_id,a.actor_email]),values.actor_id)}${values.invoice_id?`<input type="hidden" name="invoice_id" value="${esc(values.invoice_id)}"><label>Invoice<input value="${esc(state.detail?.internal_number||'Selected invoice')}" readonly></label>`:''}`:`${selectField('payment_method','Method',['cash','bank','mpesa','cheque','other'],values.payment_method)}${selectField('reversal_status','Status',['active','reversed'],values.reversal_status)}${inputField('amount_min','Payment amount from','number',values.amount_min||'','min="0" step="0.01"')}${inputField('amount_max','Payment amount to','number',values.amount_max||'','min="0" step="0.01"')}`}
 ${inv?`<div class="advanced" hidden>${inputField('due_from','Due date from','date',values.due_from||'')}${inputField('due_to','Due date to','date',values.due_to||'')}${inputField('balance_min','Balance from','number',values.balance_min||'','min="0" step="0.01"')}${inputField('balance_max','Balance to','number',values.balance_max||'','min="0" step="0.01"')}${inputField('paid_min','Collected from','number',values.paid_min||'','min="0" step="0.01"')}${inputField('paid_max','Collected to','number',values.paid_max||'','min="0" step="0.01"')}${inputField('overdue_min','Overdue days from','number',values.overdue_min||'','min="0" step="1"')}${inputField('overdue_max','Overdue days to','number',values.overdue_max||'','min="0" step="1"')}${selectField('operation_status','Action',['open','actioned','disputed'],values.operation_status)}${selectField('sort','Sort by',[['date','Latest invoice'],['name','Customer name'],['due','Due date'],['amount','Amount: highest'],['balance','Balance: highest']],values.sort)}</div>`:''}
 </div><div class="filter-bottom"><div class="actions">${inv?'<button type="button" class="filter-toggle" data-action="advanced">More filters '+icon('chevron-down')+'</button>':''}<button type="button" class="link" data-action="reset-filters">Reset</button></div><div class="actions"><span class="filter-state" id="filter-state">Unapplied</span><button type="submit" class="btn">${icon('check2')} OK</button></div></div></form>`;
}
function pager(page,count,size=50,report=false){const pages=Math.max(1,Math.ceil(count/size));return `<div class="pager"><span>${count?Math.min((page-1)*size+1,count):0}–${Math.min(page*size,count)} of ${count}</span><div class="actions">${button('Previous',report?'report-prev':'invoice-prev','secondary small','',page<=1?'disabled':'')}<span style="padding:0 9px">${page} / ${pages}</span>${button('Next',report?'report-next':'invoice-next','secondary small','',page>=pages?'disabled':'')}</div></div>`;}
async function invoices(token){
 const [data]=await Promise.all([api('/invoices/query',{method:'POST',body:{filters:state.invoiceFilters,page:state.invoicePage}}),getCustomers()]);if(token!==state.token)return;state.invoiceResult=data;
 document.querySelector('#main').innerHTML=`${heading('Invoices',writable()?button('New invoice','new-invoice','','plus-lg'):'')}${filterForm('invoices',state.invoiceFilters)}<section class="panel"><div class="panel-head"><h2>Invoice register</h2><span class="muted">${data.summary.count} invoices · ${state.currency}</span></div>${invoiceTable(data.rows)}${pager(data.page,data.summary.count)}</section>${footer()}`;
 document.querySelector('#filter-state').textContent='Applied';
}
async function customersPage(token){const customers=await getCustomers();if(token!==state.token)return;
 document.querySelector('#main').innerHTML=`${heading('Customers',writable()?button('New customer','new-customer','','plus-lg'):'')}<div class="panel"><form id="customer-search" class="search-row" style="padding-top:22px"><input name="search" type="search" placeholder="Search customers" aria-label="Search customers"> <button class="btn secondary">Search</button></form></div><div id="customer-list">${customerCards(customers)}</div>${footer()}`;
}
function customerCards(customers){return customers.length?`<div class="customer-grid">${customers.map(c=>`<article class="customer-card"><span class="avatar">${initials(c.name)}</span><h3>${esc(c.name)} ${c.archived?'<span class="tag">Archived</span>':''}</h3><small>${esc(c.customer_code)}</small><p>${esc(c.email||'—')}</p><p>${esc(c.phone||'—')}</p><div class="actions"><button class="link" data-action="customer-invoices" data-id="${c.id}">Invoices ${icon('arrow-up-right')}</button>${writable()?button('Edit','edit-customer','secondary small','',`data-id="${c.id}"`):''}</div></article>`).join('')}</div>`:empty('No customers found','people',writable()?button('New customer','new-customer','','plus-lg'):'');}
async function reportPage(token){await getCustomers();if(token!==state.token)return;const kind=state.page==='history'?'history':state.page==='collections'?'payments':'invoices';state.reportKind=kind;if(kind==='history')state.actors=await api('/history/actors');if(token!==state.token)return;
 document.querySelector('#main').innerHTML=`${heading(state.page==='reports'?'Invoice reports':label(state.page))}${filterForm(kind,state.draft)}<section class="panel"><div class="report-bar"><div class="report-note"><span class="report-emblem">${icon(kind==='history'?'clock-history':kind==='payments'?'wallet2':'file-earmark-bar-graph')}</span><div><h2>${kind==='history'?'Audit history':kind==='payments'?'Collections register':'Invoice report'}</h2><small id="report-caption">No applied report</small></div></div><div class="actions"><select id="export-format" class="export-format" aria-label="Download format"><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="pdf">PDF</option></select>${button('Download','export','','download','id="export-button" disabled')}</div></div><div id="report-results" aria-live="polite">${empty('Select filters, then OK','sliders')}</div></section>${footer()}`;
 if(state.snapshot&&state.snapshot.kind===kind){renderReport();markFilters();}
}
function markFilters(){const status=document.querySelector('#filter-state');if(status)status.innerHTML=state.dirty?'Unapplied changes':`${icon('check-circle')} Applied`;const b=document.querySelector('#export-button');if(b)b.disabled=state.dirty||!state.snapshot;}
function renderReport(){const s=state.snapshot;const page=state.reportPage||1;const rows=s.rows.slice((page-1)*50,page*50);document.querySelector('#report-caption').textContent=`${s.rows.length} records · ${timestamp(s.created_at)}`;
 const summary=Object.entries(s.summary).filter(([k])=>['count','invoiced','collected','outstanding','overdue','partial_balance'].includes(k)).map(([k,v])=>`<div class="summary-tile ${k==='overdue'?'risk':''}"><span>${label(k==='count'?'records':k)}</span><strong>${k==='count'?v:money(v)}</strong>${k==='count'?'':`<small>${state.currency}</small>`}</div>`).join('');
 const data=s.kind==='invoices'?invoiceTable(rows):s.kind==='payments'?paymentsTable(rows):historyTable(rows);
 document.querySelector('#report-results').innerHTML=`<div class="report-criteria"><div class="criteria-chips">${criteriaChips(s.filters)}</div><span class="as-of">As of ${shortDate(s.as_of_date)}</span></div><div class="snapshot-summary">${summary}</div>${s.kind==='invoices'?`<div class="report-progress"><span>Collected <strong>${s.summary.invoiced?(100*s.summary.collected/s.summary.invoiced).toFixed(1):'0.0'}%</strong></span><div class="metric-track"><span style="width:${s.summary.invoiced?100*s.summary.collected/s.summary.invoiced:0}%"></span></div><span>Outstanding <strong>${state.currency} ${money(s.summary.outstanding)}</strong></span></div>`:''}${data}${pager(page,s.rows.length,50,true)}`;
}
function paymentsTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Invoice / Source</th><th>Customer</th><th class="amount">Amount</th><th>Method</th><th>Reference</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${shortDate(r.payment_date)}</td><td><button class="link" data-action="invoice-detail" data-id="${r.invoice_id}">${esc(r.internal_number)}</button><span class="cell-sub">${esc(r.external_number||'—')}</span></td><td>${esc(r.customer_name)}</td><td class="amount">${money(r.amount)}</td><td>${label(r.method)}</td><td>${esc(r.reference||'—')}</td><td><span class="tag ${r.reversed_at?'red':'green'}">${r.reversed_at?'Reversed':'Collected'}</span></td><td>${admin()&&!r.reversed_at?button('Reverse','reverse','danger small','',`data-id="${r.id}" data-invoice="${r.invoice_id}"`):''}</td></tr>`).join('')}</tbody></table></div>`:empty('No collections found','wallet2');}
function historyTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Date & time</th><th>Action</th><th>Customer</th><th>Invoice / Source</th><th>User</th><th></th></tr></thead><tbody>${rows.map((r,index)=>`<tr><td>${timestamp(r.created_at)}</td><td>${label(r.action)}</td><td>${esc(r.customer_name||'—')}</td><td>${esc(r.invoice_number||'—')}<span class="cell-sub">${esc(r.external_number||'')}</span></td><td>${esc(r.actor_email||'—')}</td><td>${button('View','audit-detail','secondary small','',`data-index="${(state.reportPage-1)*50+index}"`)}</td></tr>`).join('')}</tbody></table></div>`:empty('No history found','clock-history');}
async function importsPage(token){const batches=await api('/imports');if(token!==state.token)return;
 document.querySelector('#main').innerHTML=`${heading('Imports',`<a class="btn secondary" href="/invoice-import-template.csv" download>${icon('download')} Template</a>`)}${writable()?`<section class="panel"><div class="panel-head"><h2>Upload invoices</h2><span class="muted">CSV / Excel · 5 MB · 5,000 rows</span></div><div class="panel-body"><div class="dropzone">${icon('cloud-arrow-up')}<h3>Select a file</h3><input id="import-file" type="file" accept=".csv,.xlsx" aria-label="Invoice file"></div><div id="import-mapping"></div></div></section><section id="import-preview"></section>`:''}<section class="panel"><div class="panel-head"><h2>Import history</h2><span class="muted">Last 100 batches</span></div>${batches.length?`<div class="table-wrap"><table><thead><tr><th>File</th><th>Date</th><th>Inserted</th><th>Updated</th><th>Status</th></tr></thead><tbody>${batches.map(b=>`<tr><td>${esc(b.file_name)}</td><td>${timestamp(b.created_at)}</td><td>${b.result?.inserted??'—'}</td><td>${b.result?.updated??'—'}</td><td><span class="tag ${b.status==='completed'?'green':'amber'}">${label(b.status)}</span></td></tr>`).join('')}</tbody></table></div>`:empty('No imports yet','cloud-arrow-up')}</section>${footer()}`;
 state.importFile=null;state.importPreview=null;
}
async function inspectFile(file){state.importFile=file;state.importPreview=null;document.querySelector('#import-preview').innerHTML='';const fd=new FormData();fd.append('file',file);const data=await api('/imports/inspect',{method:'POST',body:fd});state.importInspect=data;
 document.querySelector('#import-mapping').innerHTML=`<form id="mapping-form"><div class="mapping-grid">${data.fields.map((f,i)=>`<label>${label(f)}${i<5?' *':''}<select name="${f}"><option value="">Skip</option>${data.columns.map(c=>`<option ${data.mapping[f]===c?'selected':''} value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label>`).join('')}</div><div class="actions" style="justify-content:space-between;margin-top:22px"><small>${data.count} rows</small><button class="btn">Preview ${icon('arrow-right')}</button></div></form>`;
}
function renderImportPreview(data){const invalid=data.preview.filter(r=>r.errors.length).length;const insert=data.preview.filter(r=>!r.errors.length&&r.mode==='insert').length;const update=data.preview.filter(r=>!r.errors.length&&r.mode==='update').length;
 document.querySelector('#import-preview').innerHTML=`<section class="panel"><div class="panel-head"><h2>Import preview</h2><div class="actions">${invalid?button('Rejected rows','download-rejected','secondary','download'):''}${button('Import','commit-import','','check2',invalid?'disabled':'')}</div></div><div class="import-counts"><span><strong>${insert}</strong> New</span><span><strong>${update}</strong> Update</span><span><strong>${invalid}</strong> Rejected</span></div><div class="table-wrap"><table><thead><tr><th>Row</th><th>Customer</th><th>Source invoice</th><th>Invoice date</th><th>Due date</th><th class="amount">Amount</th><th>Result</th></tr></thead><tbody>${data.preview.slice(0,100).map(p=>`<tr><td>${p.row_number}</td><td>${esc(p.row.customer_name)}</td><td>${esc(p.row.invoice_number)}</td><td>${esc(p.row.invoice_date)}</td><td>${esc(p.row.due_date)}</td><td class="amount">${esc(p.row.amount)}</td><td>${p.errors.length?`<div class="row-error">${esc(p.errors.join('; '))}</div>`:`<span class="tag ${p.mode==='insert'?'green':'blue'}">${label(p.mode)}</span>`}</td></tr>`).join('')}</tbody></table></div><div class="pager">${Math.min(100,data.preview.length)} of ${data.preview.length} preview rows</div></section>`;
}
async function teamPage(token){const members=await api('/team');if(token!==state.token)return;state.team=members;
 document.querySelector('#main').innerHTML=`${heading('Team',button('Add member','new-member','','person-plus'))}<section class="panel">${members.length?`<div class="table-wrap"><table><thead><tr><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>${members.map(m=>`<tr><td>${esc(m.email)}</td><td>${label(m.role)}</td><td><span class="tag ${m.active?'green':''}">${m.active?'Active':'Disabled'}</span></td><td>${m.role!=='owner'&&m.user_id!==state.session.user.id&&(state.role==='owner'||m.role!=='admin')?button('Edit','edit-member','secondary small','',`data-id="${m.user_id}"`):''}</td></tr>`).join('')}</tbody></table></div>`:''}</section>${footer()}`;
}
function openModal(title,body,foot=''){modal.innerHTML=`<div class="modal-head"><h2>${esc(title)}</h2><button class="icon-btn" data-action="close-modal" aria-label="Close">${icon('x-lg')}</button></div>${body}${foot}`;if(!modal.open)modal.showModal();}
const formButtons=(text='Save')=>`<div class="modal-footer">${button('Cancel','close-modal','secondary','', 'type="button"')}<button class="btn" type="submit">${text}</button></div>`;
function formError(){return '<div class="error form-error" id="form-error" role="alert"></div>';}
function customerForm(c={}){
 const code=c.customer_code||`CUS-${crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`;
 openModal(c.id?'Edit customer':'New customer',`<form id="customer-form" data-id="${c.id||''}" data-version="${c.version||''}"><div class="modal-body form-grid">${formError()}${inputField('name','Name','text',c.name||'','required maxlength="160"')}${inputField('customer_code','Customer code','text',code,c.id?'readonly':'required maxlength="80"')}${inputField('email','Email','email',c.email||'','maxlength="254"')}${inputField('phone','Phone','tel',c.phone||'','maxlength="60"')}<label class="span-2">Notes<textarea name="notes" maxlength="4000">${esc(c.notes||'')}</textarea></label>${c.id?`<label><select name="archived"><option value="false">Active</option><option value="true" ${c.archived?'selected':''}>Archived</option></select></label>`:''}</div>${formButtons()}</form>`);
}
async function invoiceForm(inv={}){
 await getCustomers();const active=state.customers.filter(c=>!c.archived||c.id===inv.customer_id);
 if(!active.length){customerForm();toast('Create a customer first');return;}
 openModal(inv.id?'Edit invoice':'New invoice',`<form id="invoice-form" data-id="${inv.id||''}" data-version="${inv.version||''}" data-request="${crypto.randomUUID()}"><div class="modal-body form-grid">${formError()}${!inv.id?`<label class="span-2">Find customer<input type="search" id="invoice-customer-search" placeholder="Name or customer code"></label>`:''}<label class="span-2">Customer<select name="customer_id" required ${inv.id?'disabled':''}><option value="">Select customer</option>${active.map(c=>`<option value="${c.id}" ${inv.customer_id===c.id?'selected':''}>${esc(c.name)} · ${esc(c.customer_code)}</option>`).join('')}</select>${inv.id?`<input type="hidden" name="customer_id" value="${inv.customer_id}">`:''}</label>${inputField('external_number','Source invoice number','text',inv.external_number||'','maxlength="100"')}${inputField('internal_number','Invoice ID','text',inv.internal_number||'Assigned on save','disabled')}${inputField('invoice_date','Invoice date','date',inv.invoice_date||today(),'required')}${inputField('due_date','Due date','date',inv.due_date||today(),'required')}${inputField('amount',`Amount (${state.currency})`,'number',inv.amount||'','required min="0.01" step="0.01"')}${selectField('operation_status','Action status',['open','actioned','disputed'],inv.operation_status||'open')}<label class="span-2">Notes<textarea name="notes" maxlength="4000">${esc(inv.notes||'')}</textarea></label></div>${formButtons()}</form>`);
}
async function invoiceDetail(id){const {invoice:r,payments}=await api(`/invoices/${id}`);state.detail=r;
 openModal(r.internal_number,`<div class="modal-body"><div class="actions" style="justify-content:space-between"><h2>${esc(r.customer_name)}</h2>${statuses(r)}</div><div class="detail-numbers"><div><small>Invoiced · ${state.currency}</small><strong>${money(r.amount)}</strong></div><div><small>Collected</small><strong>${money(r.paid_amount)}</strong></div><div><small>Balance</small><strong>${money(r.balance)}</strong></div></div><div class="detail-grid"><div><label>Source invoice</label><p>${esc(r.external_number||'—')}</p></div><div><label>Customer code</label><p>${esc(r.customer_code)}</p></div><div><label>Invoice date</label><p>${shortDate(r.invoice_date)}</p></div><div><label>Due date</label><p>${shortDate(r.due_date)}</p></div><div><label>Action</label><p>${label(r.operation_status)}</p></div></div>${r.notes?`<div class="notes">${esc(r.notes)}</div>`:''}<div class="actions" style="margin-bottom:25px">${writable()?button('Edit invoice','edit-invoice','secondary','pencil',`data-id="${r.id}"`):''}${writable()&&r.balance>0?button('Record collection','collect','','plus-lg',`data-id="${r.id}"`):''}${button('History','invoice-history','secondary','clock-history',`data-id="${r.id}"`)}</div><h3>Collections</h3>${payments.length?payments.map(p=>`<div class="payment-row"><div><strong>${state.currency} ${money(p.amount)}</strong> <span class="tag ${p.reversed_at?'red':'green'}">${p.reversed_at?'Reversed':label(p.method)}</span><small>${shortDate(p.payment_date)} · ${esc(p.reference||'—')}</small>${p.reversed_at?`<small>${esc(p.reversal_reason)}</small>`:''}</div><div class="actions">${admin()&&!p.reversed_at?button('Reverse','reverse','danger small','',`data-id="${p.id}" data-invoice="${r.id}"`):''}</div></div>`).join(''):empty('No collections recorded','wallet2')}</div>`);
}
async function paymentForm(id){const {invoice:r}=await api(`/invoices/${id}`);if(r.balance<=0){toast('Invoice is already paid');return;}
 openModal('Record collection',`<form id="payment-form" data-id="${id}" data-key="${crypto.randomUUID()}"><div class="modal-body"><h3>${esc(r.internal_number)} · ${esc(r.customer_name)}</h3><div class="detail-numbers"><div><small>Balance · ${state.currency}</small><strong>${money(r.balance)}</strong></div></div><div class="form-grid">${formError()}${inputField('amount',`Amount (${state.currency})`,'number','','required min="0.01" step="0.01" max="'+r.balance+'"')}${inputField('payment_date','Payment date','date',today(),'required min="'+r.invoice_date+'" max="'+today()+'"')}<label>Method<select name="method" required>${['mpesa','bank','cash','cheque','other'].map(m=>`<option value="${m}">${label(m)}</option>`).join('')}</select></label>${inputField('reference','Reference','text','','maxlength="160"')}<label class="span-2">Notes<textarea name="notes" maxlength="4000"></textarea></label></div></div>${formButtons('Record collection')}</form>`);
}
function reverseForm(id,invoice){openModal('Reverse collection',`<form id="reverse-form" data-id="${id}" data-invoice="${invoice}"><div class="modal-body">${formError()}<label>Reason<textarea name="reason" required maxlength="1000"></textarea></label></div>${formButtons('Reverse')}</form>`);}
function memberForm(m={}){openModal(m.user_id?'Edit member':'Add member',`<form id="member-form"><div class="modal-body form-grid">${formError()}${inputField('email','Email','email',m.email||'',`required ${m.user_id?'readonly':''}`)}<label>Role<select name="role">${(state.role==='owner'?['admin','collector','viewer']:['collector','viewer']).map(role=>`<option value="${role}" ${m.role===role?'selected':''}>${label(role)}</option>`).join('')}</select></label><label>Status<select name="active"><option value="true">Active</option><option value="false" ${m.active===false?'selected':''}>Disabled</option></select></label></div>${formButtons()}</form>`);}
async function download(route,name){const response=await api(route,{blob:true});const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function applyFilters(form){const values=Object.fromEntries(new FormData(form));
 if(state.page==='invoices'){state.invoiceFilters=values;state.invoicePage=1;await loadPage();}
 else {const token=state.token,kind=state.reportKind;const result=await api('/reports/apply',{method:'POST',body:{kind,filters:values}});if(token!==state.token||!form.isConnected)return;const current=Object.fromEntries(new FormData(form));state.snapshot=result;state.draft=current;state.dirty=JSON.stringify(current)!==JSON.stringify(values);state.reportPage=1;renderReport();markFilters();}
}
async function refreshAfterWrite(){state.snapshot=null;state.dirty=true;await loadPage();}
async function handleAction(btn){const action=btn.dataset.action,id=btn.dataset.id;
 if(action==='menu'){document.querySelector('.sidebar').classList.toggle('open');return;}
 if(action==='close-modal'){modal.close();return;}
 if(action==='signout'){await state.client.auth.signOut();state.session=null;state.org=null;state.snapshot=null;state.overviewFilters={};state.overviewDraft={};state.overviewData=null;state.overviewRequest++;clearTimeout(state.overviewTimer);login();return;}
 if(action==='reload'){await loadPage();return;}
 if(action==='new-customer'){customerForm();return;}
 if(action==='edit-customer'){customerForm(state.customers.find(c=>c.id===id));return;}
 if(action==='new-invoice'){await invoiceForm();return;}
 if(action==='edit-invoice'){await invoiceForm(state.detail);return;}
 if(action==='invoice-detail'){await invoiceDetail(id);return;}
 if(action==='collect'){await paymentForm(id);return;}
 if(action==='reverse'){reverseForm(id,btn.dataset.invoice);return;}
 if(action==='goto-import'){location.hash='imports';return;}
 if(action==='customer-invoices'){state.invoiceFilters={customer_id:id};state.invoicePage=1;location.hash='invoices';return;}
 if(action==='overdue-invoices'){state.invoiceFilters={...state.overviewFilters,due_status:'overdue'};state.invoicePage=1;location.hash='invoices';return;}
 if(action==='invoice-history'){modal.close();state.draft={invoice_id:id};state.snapshot=null;state.dirty=true;location.hash='history';return;}
 if(action==='advanced'){const a=document.querySelector('.advanced');a.hidden=!a.hidden;btn.innerHTML=`${a.hidden?'More':'Fewer'} filters ${icon(a.hidden?'chevron-down':'chevron-up')}`;return;}
 if(action==='reset-filters'&&state.page==='overview'){const form=document.querySelector('#overview-filter-form');form.querySelectorAll('input,select').forEach(el=>el.value='');document.querySelector('#overview-period').value='custom';await applyOverview(form);return;}
 if(action==='reset-filters'){const form=document.querySelector('#filter-form');form.querySelectorAll('input,select').forEach(el=>el.value='');state.draft={};state.dirty=true;markFilters();return;}
 if(action==='invoice-prev'||action==='invoice-next'){state.invoicePage+=action==='invoice-prev'?-1:1;await loadPage();return;}
 if(action==='report-prev'||action==='report-next'){state.reportPage+=action==='report-prev'?-1:1;renderReport();return;}
 if(action==='export'){if(state.dirty||!state.snapshot)return;const f=document.querySelector('#export-format').value;await download(`/reports/${state.snapshot.id}/export?format=${f}`,`mary-${state.snapshot.kind}-${state.snapshot.as_of_date}.${f}`);return;}
 if(action==='download-rejected'){await download(`/imports/${state.importPreview.id}/rejected`,'rejected-rows.csv');return;}
 if(action==='commit-import'){const result=await api(`/imports/${state.importPreview.id}/commit`,{method:'POST',body:{}});toast(`${result.inserted} inserted · ${result.updated} updated`);await refreshAfterWrite();return;}
 if(action==='new-member'){memberForm();return;}
 if(action==='edit-member'){memberForm(state.team.find(m=>m.user_id===id));return;}
 if(action==='audit-detail'){const event=state.snapshot.rows[Number(btn.dataset.index)];openModal(label(event.action),`<div class="modal-body"><div class="detail-grid"><div><label>Date</label><p>${timestamp(event.created_at)}</p></div><div><label>User</label><p>${esc(event.actor_email)}</p></div></div><h3>Before</h3><pre class="audit-json">${esc(JSON.stringify(event.before_data,null,2))}</pre><h3>After</h3><pre class="audit-json">${esc(JSON.stringify(event.after_data,null,2))}</pre></div>`);return;}
 if(action==='forgot'){const email=document.querySelector('#login-form [name=email]').value;if(!email){document.querySelector('#login-error').textContent='Enter your email';return;}const {error}=await state.client.auth.resetPasswordForEmail(email,{redirectTo:location.origin});if(error)throw error;toast('Password reset email requested');}
}
document.addEventListener('click',async e=>{const btn=e.target.closest('[data-action]');if(!btn||btn.disabled)return;const wasDisabled=btn.disabled;try{btn.disabled=true;await handleAction(btn);}catch(error){toast(error.message);}finally{if(btn.isConnected)btn.disabled=wasDisabled;}});
document.addEventListener('input',e=>{if(e.target.id==='invoice-customer-search'){clearTimeout(state.customerTimer);const term=e.target.value;state.customerTimer=setTimeout(async()=>{try{const list=await api(`/customers?search=${encodeURIComponent(term)}`);const select=modal.querySelector('[name=customer_id]');if(select&&modal.querySelector('#invoice-customer-search')?.value===term)select.innerHTML='<option value="">Select customer</option>'+list.filter(c=>!c.archived).map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.customer_code)}</option>`).join('');}catch(err){toast(err.message);}},250);}if(e.target.closest('#overview-filter-form')){document.querySelector('#overview-period').value='custom';queueOverview(e.target.closest('form'));}if(e.target.closest('#filter-form')){state.draft=Object.fromEntries(new FormData(document.querySelector('#filter-form')));state.dirty=true;markFilters();}});
document.addEventListener('change',async e=>{try{if(e.target.id==='overview-period'){const form=document.querySelector('#overview-filter-form'),date=today(),year=Number(date.slice(0,4)),month=Number(date.slice(5,7));const from=e.target.value==='month'?date.slice(0,7)+'-01':e.target.value==='year'?year+'-01-01':e.target.value==='quarter'?new Date(Date.UTC(year,month-3,1)).toISOString().slice(0,10):'';form.elements.date_from.value=from;form.elements.date_to.value=from?date:'';await applyOverview(form);}if(e.target.id==='import-file'&&e.target.files[0])await inspectFile(e.target.files[0]);if(e.target.id==='org-select'){const m=state.memberships.find(m=>m.org_id===e.target.value);state.org=m.org_id;state.role=m.role;state.currency=m.mc_organizations.currency;state.snapshot=null;state.invoiceFilters={};state.draft={};state.overviewFilters={};state.overviewDraft={};state.overviewData=null;state.overviewRequest++;state.dirty=true;await loadPage();}}catch(err){toast(err.message);}});
document.addEventListener('submit',async e=>{
 const form=e.target;e.preventDefault();const submit=form.querySelector('button[type=submit]')||form.querySelector('button:not([type])');if(submit)submit.disabled=true;const values=Object.fromEntries(new FormData(form));const errorBox=form.querySelector('.error');if(errorBox)errorBox.textContent='';
 try{
  if(form.id==='login-form'){const {data,error}=await state.client.auth.signInWithPassword(values);if(error)throw error;state.session=data.session;await connect();}
  else if(form.id==='recovery-form'){const {error}=await state.client.auth.updateUser({password:values.password});if(error)throw error;modal.close();toast('Password updated');await connect();}
  else if(form.id==='overview-filter-form'){await applyOverview(form);}
  else if(form.id==='filter-form'){await applyFilters(form);}
  else if(form.id==='customer-search'){const data=await api(`/customers?search=${encodeURIComponent(values.search)}`);state.customers=data;document.querySelector('#customer-list').innerHTML=customerCards(data);}
  else if(form.id==='mapping-form'){const fd=new FormData();fd.append('file',state.importFile);fd.append('mapping',JSON.stringify(values));state.importPreview=await api('/imports/preview',{method:'POST',body:fd});renderImportPreview(state.importPreview);}
  else if(form.id==='customer-form'){values.archived=values.archived==='true';if(form.dataset.id)values.version=Number(form.dataset.version);await api(`/customers${form.dataset.id?'/'+form.dataset.id:''}`,{method:form.dataset.id?'PUT':'POST',body:values});modal.close();toast('Customer saved');await refreshAfterWrite();}
  else if(form.id==='invoice-form'){if(form.dataset.id)values.version=Number(form.dataset.version);values.request_id=form.dataset.request;await api(`/invoices${form.dataset.id?'/'+form.dataset.id:''}`,{method:form.dataset.id?'PUT':'POST',body:values});modal.close();toast('Invoice saved');await refreshAfterWrite();}
  else if(form.id==='payment-form'){values.idempotency_key=form.dataset.key;await api(`/invoices/${form.dataset.id}/payments`,{method:'POST',body:values});modal.close();toast('Collection recorded');await refreshAfterWrite();}
  else if(form.id==='reverse-form'){await api(`/payments/${form.dataset.id}/reverse`,{method:'POST',body:values});modal.close();toast('Collection reversed');await refreshAfterWrite();}
  else if(form.id==='member-form'){values.active=values.active==='true';await api('/team',{method:'POST',body:values});modal.close();toast('Member saved');await refreshAfterWrite();}
 }catch(err){if(errorBox)errorBox.textContent=err.message;else toast(err.message);}finally{if(submit?.isConnected)submit.disabled=false;}
});
window.addEventListener('hashchange',()=>{if(state.session&&state.org){state.snapshot=null;state.dirty=true;if(!['history','reports','collections'].includes(location.hash.slice(1)))state.draft={};loadPage();}});
function login(error=''){
 root.innerHTML=`<div class="login"><div class="login-art"><div class="brand"><img src="/mark.svg" alt=""><div><strong>Mary</strong><span>Collections</span></div></div><h1>Every invoice.<br><span>Accounted for.</span></h1><div class="login-lines"><div></div><div></div><div></div><div></div></div></div><div class="login-form"><form id="login-form"><div class="eyebrow">Mary Collections</div><h2>Sign in</h2><div class="error" id="login-error" role="alert">${esc(error)}</div>${inputField('email','Email','email','','required autocomplete="username"')}${inputField('password','Password','password','','required autocomplete="current-password"')}<button type="submit" class="btn">Sign in ${icon('arrow-right')}</button><button type="button" class="link" data-action="forgot">Forgot password</button></form></div></div>`;
}
async function connect(){
 const data=await api('/session');state.memberships=data.memberships;if(!state.memberships.length){login('No workspace access. Contact your administrator.');return;}
 const selected=state.memberships.find(m=>m.org_id===state.org)||state.memberships[0];state.org=selected.org_id;state.role=selected.role;state.currency=selected.mc_organizations.currency;
 await loadPage();
}
async function boot(){try{const response=await fetch('/api/config');if(!response.ok)throw new Error('Backend unavailable');const cfg=await response.json();if(!cfg.supabaseUrl||!cfg.supabaseKey||cfg.supabaseUrl.includes('YOUR_PROJECT'))throw new Error('Supabase is not configured');state.client=createClient(cfg.supabaseUrl,cfg.supabaseKey);
 state.client.auth.onAuthStateChange((event,session)=>{state.session=session;if(event==='PASSWORD_RECOVERY'){setTimeout(()=>openModal('Set new password',`<form id="recovery-form"><div class="modal-body">${formError()}${inputField('password','New password','password','','required minlength="10" autocomplete="new-password"')}</div>${formButtons('Update password')}</form>`),0);}if(event==='SIGNED_OUT'){state.org=null;login();}});
 const {data}=await state.client.auth.getSession();state.session=data.session;if(state.session)await connect();else login();
 }catch(e){login(e.message);document.querySelectorAll('#login-form button').forEach(b=>b.disabled=true);}}
boot();
